### ISSUE TITLE
OpenWRT: Malformed JSON-UDP stream (when JSON string length is longer than 1024 bytes)

### ISSUE THREAD

**Issue by verzulli** [utoni/nDPId#10]
I just built and installed the OpenWRT package of `nDPId` built on commit 36f1786b. I upgraded my previous nDPId, as I understood that the JSON format could have been upgraded (as for this [PR #1725 on the nDPI project](https://github.com/ntop/nDPI/pull/1725))

Unfortunately, some of the JSON coming out from current release are malformed: they seems to be "truncated" to 1024 chars. As such, if they are longer.. and gets truncated, they actually comes "joined" with next one, generating a malformed *unique* JSON (due to missing double quotes, commas and, for sure, the final `}`.
I'm attaching a JSON-file obtained via a raw `netcat`, redirecting the output on a file. As you can see, for every row beginning with a number bigger than 1024... there is a problem.

Can you confirm the problem is on the source side? Or should I have been done something on the openwrt-package-building side?

Thanks,
DV

[a.zip](https://github.com/utoni/nDPId/files/9637221/a.zip)

**Comment by utoni** [comment]
I can confirm that there is an issue in with the JSON *deserializer* (not the nDPI *serializer*) in `dependencies/nDPIsrvd.h`. This issue persists since I wrote the `jsmn` integration. But you should only be affected if you are using one of the examples that make use of the C API (examples prefixed with `c-`).

One important thing to mention is the changed maximum size of the network buffer. It changed some commits ago from `16384` to `32768` bytes. Your client app needs to be ready to receive  `32768` bytes per `recvfrom()` syscall (or any similiar syscall).

**Comment by utoni** [comment]
Can you try to capture a pcap and upload it together with the json file? I want to check something.

**Comment by verzulli** [comment]
Sorry! My fault!

The problem I described was brought in by `netcat` (...that I used to capture the L7-JSON-string) while trying to get out my `rt-analyzer` out of the loop. Probably `netcat` suffers from the receive buffer lenght size you mentioned.

While checking better my application (`ndpid-rt-analyzer`) I saw that it behaves **correctly** (so, we can say that NodeJS properly handle such change **without** any intervention required on the application code side).

In the end: I was simply wrong. Sorry! (the issue I was dealing with, on my side, was related to a totally different think)

BTW: I'm attaching the PCAP file you requested. As you can see on packet 84, 85, 86 ,related payload included all the required JSON-structure (and they all are bigger than 1024 chars).
![Screenshot_20220924_090814](https://user-images.githubusercontent.com/6765895/192085057-30735bc4-a8d7-4df9-9acc-db57e6968f5a.png)

[out2.pcap.zip](https://github.com/utoni/nDPId/files/9638128/out2.pcap.zip)
