### ISSUE TITLE
Signal Voip on Fastweb Napoli ?

### ISSUE THREAD

**Issue by harut420** [utoni/nDPId#22]
Hi, 
I am very curious about this output, 
it seems that signal connects to fastweb .... which seems impossible to me.

![1](https://github.com/utoni/nDPId/assets/49169029/ee6b6c38-0f67-47ad-86e9-0689b965ba82)

**Comment by utoni** [comment]
I think you are at the wrong place for this issue. It is either related to [ntopng](https://github.com/ntop/ntopng) or [nDPI](https://github.com/ntop/nDPI).
