### ISSUE TITLE
Require libndpi >= 4.7.0 while the last release of libndpi is 4.6.0 ? 

### ISSUE THREAD

**Issue by fateme81** [utoni/nDPId#23]
First i installed the last version of libnDPI based on Github :
[https://github.com/ntop/nDPI/branches/stale](url)
and it's version is 4.6.0 however the required version of libndpi for your software is '>= 4.7.0' how that can happens? 

i got the following error : 

> Package dependency requirement 'libndpi >= 4.7.0' could not be satisfied.
> Package 'libndpi' has version '4.6.0', required version is '>= 4.7.0

**Comment by utoni** [comment]
Due to non-compatible API changes in `libnDPI`, you'll either need to use `cmake -DBUILD_NDPI=1` or use an older commit of `nDPId`.

**Comment by fateme81** [comment]
cmake -DBUILD_NDPI=1 worked for me. 
TNX
