### ISSUE TITLE
Conf file

### ISSUE THREAD

**Issue by UnveilTech** [utoni/nDPId#41]
Hi Toni,
sorry for posting here a request...

we would like to propose a new feature with the nDPId, a special argument for a .conf file instead of having all options on the command line.
we could have something like that:
- command: **./nDPId -x /etc/nDPId/nDPId.conf**
- (**-x** or **-C** or whatever you think it should be fine with you)
- nDPId.conf file including options:
interface=eth0
logfile=/var/log/nDPId/ndpid.log
socket=/tmp/ndpid-collector.sock or 127.0.0.1:7000
background=yes
protofile=/etc/nDPId/myprotos.txt
etc...

it could also be nice to have a special compilation option (ex: -DCONF_FILE=/etc/nDPId/nDPId.conf)

do you think it makes sense to you ?

have a nice day,
Fred

**Comment by utoni** [comment]
I had this already in my mind. But I thought nobody would be interested in having this feature. Will do ASAP.

**Comment by UnveilTech** [comment]
Toni,
it will be readable and useful :o)
then all popular products use that way with settings...

not an emmergency, just a "nice-to-have".

bye Fred

**Comment by UnveilTech** [comment]
Toni,

giving a try, we keep you posted once compiled and started...

bye Fred

**Comment by utoni** [comment]
Thanks! Hoping to get some feedback from you guys! (positive and negative) :smile_cat:

**Comment by UnveilTech** [comment]
compiled, launched, it seems all is ok........................... for the moment.
-R and -f work fine.

we keep it running in our lab for a while, we keep you posted.
anyway, thanks a lot for your work  !!!

bye Fred

**Comment by UnveilTech** [comment]
by "actualy the values (from the json) of 'flow_id' and 'flow_first_seen' are incoherent", we mean values are always the same and sizes are increasing with incoherent value...

**Comment by UnveilTech** [comment]
Toni,
here is the settings working fine with us:

[general]
...
internal=false
external=false
compression=true
analysis=false

[tuning]
max-flows-per-thread=2048
max-idle-flows-per-thread=64
max-reader-threads=10
daemon-status-interval=600000000
#memory-profiling-log-interval=5
compression-scan-interval=20000000
compression-flow-inactivity=30000000
flow-scan-interval=10000000
generic-max-idle-time=600000000
icmp-max-idle-time=120000000
tcp-max-idle-time=180000000
udp-max-idle-time=7440000000
tcp-max-post-end-flow-time=120000000
max-packets-per-flow-to-send=15
max-packets-per-flow-to-process=32
max-packets-per-flow-to-analyse=32
error-event-threshold-n=16
error-event-threshold-time=10000000

[ndpi]
packets_limit_per_flow=32
flow.direction_detection=enable
flow.track_payload=disable
tcp_ack_payload_heuristic=disable
fully_encrypted_heuristic=enable
libgcrypt.init=1
dpi.compute_entropy=1
fpc=enable       # you set it 'disable'
dpi.guess_on_giveup=0x03
flow_risk_lists.load=1
flow_risk.crawler_bot.list.load=1
log.level=0

[protos]
tls.certificate_expiration_threshold=30     # we set it back to default
tls.application_blocks_tracking=disable    # we set it back to default
stun.max_packets_extra_dissection=25    # we set it back to default


bye Fred

**Comment by utoni** [comment]
Hi Fred

> we have used the 'ndpid.conf.example' (renamed ndpid.conf) you provide with the original source but those 3 options seems to act not correctly, we did not use them with previous builds: _#internal = true #external = true analysis = true_
> 
> we kept 'internal' and 'external' commented so it means not enabled in the settings. but the option '**analysis**' seems not working properly, actualy the values (from the json) of '**flow_id**' and '**flow_first_seen**' are incoherent, indicating many MB up to many GB with protos (ex: ICMP, DNS, ...). we have not those strange values with the command line, surely because those options are 'false' by default.

If the `analysis` mode is enabled, the daemon will consume much more heap memory. The reason behind that is that it needs additional memory necessary to store some statistical values until `max-packets-per-flow-to-analyse` reached before firing an `analyse` event which contains all those statistical values. The heap memory used for that is free'd afterwards.

> by "actualy the values (from the json) of 'flow_id' and 'flow_first_seen' are incoherent", we mean values are always the same and sizes are increasing with incoherent value...

That's something I do not understand. Could you please elaborate this more (or provide an example)?

**Comment by utoni** [comment]
But I'll comment out `analysis = true`, which will disable the analysis completely and add some comments about memory consumption.

**Comment by UnveilTech** [comment]
> > by "actualy the values (from the json) of 'flow_id' and 'flow_first_seen' are incoherent", we mean values are always the same and sizes are increasing with incoherent value...
> 
> That's something I do not understand. Could you please elaborate this more (or provide an example)?

Ya I know, not easy to understand, we spent hours to see the issue and tried to identify where the problem could be.
let me summarize what we saw:
- using your .conf with default values we got results with many strange values
- we first have commented the part [protos], same (wrong) results
- then we have commented [ndpi], then [tuning] ([tuning] seem to be default values), same result
- finally, set to false 'internal', 'external' and 'analysis', here results were correct

what I mean by 'corect' is that the key 'flow_id' to follow detected/update/end-idle is correct to get the hostname and the final size (case: https://github.com/utoni/nDPId/issues/39).
but with the default values of the ndpid.conf, the same key 'flow_id' was (many) often the same giving incoherent results as indicated.
we suspect the cause is the key 'analysis' that is, if I'm right, a recent option with the libnDPI

right now, we only use [] with that:

**Comment by UnveilTech** [comment]
more infos:

we have not found all options in the nDPId.c like 'fpc' in the section [ndpi]
regarding 'fpc', you use 'disable' but 'libnDPI/doc/configuration_parameters.md' use 'enable'

**Comment by utoni** [comment]
I've just tested the `analyse` event within `nDPId-test.c`. It works on my side.

You may test this as well on your side by changing:

```C
set_cmdarg_boolean(&nDPId_options.enable_data_analysis, 1);
```

to

```C
set_cmdarg_boolean(&nDPId_options.enable_data_analysis, 0);
```

in `nDPId-test.c:1671`.

You may then run `./test/run_tests.sh ./libnDPI ./path/to/nDPId-test` and use `git diff` afterwards to take a closer look what test results have been changed. Only `analyse` events should disappear.

> we have not found all options in the nDPId.c like 'fpc' in the section [ndpi]
regarding 'fpc', you use 'disable' but 'libnDPI/doc/configuration_parameters.md' use 'enable'

That's something I'll need to take a closer look. But from my understanding, `fpc` provides a faster packet classification, but may result in false-positives in some corner cases.

**Comment by UnveilTech** [comment]
Toni,
have a look:
<img width="569" alt="nDPId" src="https://github.com/user-attachments/assets/fa2291ef-66c4-48e9-87a0-bf8eeaf8ad8b">

ICMP: 1.3MB with 2 hits in the last 7 seconds.
something is wrong here :o)

Fred

**Comment by utoni** [comment]
> it seems the 'flow_id' becomes crazy using very old values when it should and id 2,000+ so after a while, a proto is with a strange (too big) size value.

I guess that I understood your problem now. The behavior you're mentioned regarding the `flow_id` is totally legit. Let's take a close look.
The event name that contains that low/old `flow_id` is called `update`. According to the documentation:
```txt
update: inform nDPIsrvd or other apps about a long-lasting flow, whose detection was finished a long time ago but is still active
```
 
> 'fpc' could generate some false-positives, ok but it seems not used by the nDPId.c.

That's correct. I am currently testing the `fpc` behavior.

**Comment by utoni** [comment]
> Toni, have a look: <img alt="nDPId" width="569" src="https://private-user-images.githubusercontent.com/14853003/377872535-fa2291ef-66c4-48e9-87a0-bf8eeaf8ad8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTYxNzEsIm5iZiI6MTcyOTI1NTg3MSwicGF0aCI6Ii8xNDg1MzAwMy8zNzc4NzI1MzUtZmEyMjkxZWYtNjZjNC00OGU5LTg3YTAtYmY4ZWVhZjhhZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOGIzOWUwMWRjYzkxYmEyMzU5YTllNWYxMzU4Yzk5NDVmOGVhNTY1MjdmZGY4NGM1YTBmMDI1NWM0ODdiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wOOwJEzXUQWHHtjRE0Y2VeDe0XTGW_sJlEcey0bX4-I">
> 
> ICMP: 1.3MB with 2 hits in the last 7 seconds. something is wrong here :o)
> 

Regarding the ICMP flow (also from the `README.md`)
```txt
Other protocols e.g. ICMP/ICMPv6 lack relevance for DPI, thus nDPId does not distinguish between different ICMP/ICMPv6 flows coming from the same host. This saves memory and performance, but might change in the future.
```

**Comment by UnveilTech** [comment]
I do not agree, we get ICMP and ICMPv6 from the nDPId, have a look:
<img width="569" alt="nDPId2" src="https://github.com/user-attachments/assets/38a00524-5a66-470d-9531-4f48685f9e7b">

> >update: inform nDPIsrvd or other apps about a long-lasting flow, whose detection was finished a long time ago but is still active

long time ago could mean 2+ hours ago ? hmmm, I'm not sure about that ;o)

Fred

**Comment by UnveilTech** [comment]
Toni,
additional tests done, we suspect the issue is in that part:
[protos]
tls.certificate_expiration_threshold = 7
tls.application_blocks_tracking      = enable
stun.max_packets_extra_dissection    = 8

original values from libnDPI (libnDPI/doc/configuration_parameters.md) are like that:
[protos]
tls.certificate_expiration_threshold = 30
tls.application_blocks_tracking      = disable
stun.max_packets_extra_dissection    = 25

using libnDPI values ([protos]), results look correct but we keep a look on data...

Fred

**Comment by utoni** [comment]
I'll reopen the issue for although it might be better to split the issue into two.

**Comment by utoni** [comment]
You may now use branch https://github.com/utoni/nDPId/tree/tmp and run `./test/run_config_tests.sh` to test certain configurations placed in `./test/configs`.

**Comment by UnveilTech** [comment]
hello Toni,

here is the test:
<img width="710" alt="nDPId-test" src="https://github.com/user-attachments/assets/4d10116c-493c-4025-8e80-ac217c79afd0">

does it look ok ?

bye Fred

**Comment by utoni** [comment]
It does. Closing the issue. Please open a new one if your problem persists.
