### ISSUE TITLE
'ndpi_load_risk_domain_file' (option -r) seems missing

### ISSUE THREAD

**Issue by UnveilTech** [utoni/nDPId#45]
Hello Toni,

do you think you could add the function "**ndpi_load_risk_domain_file**" to the nDPId ?
-> https://www.ntop.org/guides/nDPI/api/function_ndpi__api_8h_1a0779c379f79eb8af03d53f1a102d0baa.html

the nDPI lib uses the arg "_-r ./example/risky_domains.txt_" but it seems missing with the nDPId...

thanks,
bye Fred

**Comment by utoni** [comment]
Yea, having a PR would be great.

**Comment by UnveilTech** [comment]
what does PR mean ?

**Comment by utoni** [comment]
It's an abbreviation for "Pull Request", but I personally prefer "Merge Request" or MR which is more accurate.

**Comment by UnveilTech** [comment]
Toni,

no idea how the PR works...

attached is our zipped (no pwd) version, comment noted as "UT" what we've added...
[nDPId.zip](https://github.com/user-attachments/files/17351311/nDPId.zip)

bye Fred

**Comment by utoni** [comment]
Thanks for adding the feature to nDPId!

You're fix will be soon merged to main (See #41).

**Comment by UnveilTech** [comment]
great, you rock man :o)
