### ISSUE TITLE
Option SID to identify the server...

### ISSUE THREAD

**Issue by UnveilTech** [utoni/nDPId#46]
Hello Toni,
proposal from our side, an unique SID (UUID) to identify the server/machine.

we know we could use the flag 'Alias' but we would like to use that flag for another work.

suggestion:
- use "**cat /sys/class/dmi/id/product_uuid**" by default for the unique SID identification
- or use a special argument (ex: **-U** or **-D** or other) or from the ndpid.conf (sid/uuid=blablabla...)

what do you think ?

bye Fred

**Comment by utoni** [comment]
Hi Fred,

that's a great idea. I'll take a look how this could be integrated in nDPId.

Thanks!

**Comment by UnveilTech** [comment]
Hi Toni,
appreciated, thanks :o)

we'll post a new suggestion very soon, you should like it too...

bye Fred

**Comment by utoni** [comment]
Just to clarify: You want an extra JSON element i.e. `"uuid": "XXXX.."` in addition to the already existing `"alias": "host.tld"` as part of all events, right?

**Comment by UnveilTech** [comment]
Hi Toni,
100% correct

bye Fred

**Comment by UnveilTech** [comment]
hello Toni,
we've added the UUID, commented "// UT"
[nDPId.zip](https://github.com/user-attachments/files/17539549/nDPId.zip)
please check it fits your policies...

bye Fred

**Comment by utoni** [comment]
Thanks Fred. I am already integrating and extending your patch. :)

**Comment by UnveilTech** [comment]
you're welcome Toni ;o)

we're also having a look to the encrypt/decrypt (OpenSSL AES), it does not seem to be easy to find the right C code...

bye Fred

**Comment by utoni** [comment]
With commit https://github.com/utoni/nDPId/commit/817559ffa7ddd1c3e71c9b2b0d862c381bafd5f6 it is now possible to use UUID for every nDPId instance. Please give me some feedback. :)

**Comment by UnveilTech** [comment]
Toni,
looks great, thanks a lot.

bye Fred
